export enum WorkflowState {
  CREATED = "CREATED",
  VALIDATING = "VALIDATING",
  QUEUED = "QUEUED",
  LEASED = "LEASED",
  EXECUTING = "EXECUTING",
  VALIDATING_OUTPUT = "VALIDATING_OUTPUT",
  COMPLETED = "COMPLETED",
  FAILED_RETRYABLE = "FAILED_RETRYABLE",
  FAILED_FATAL = "FAILED_FATAL",
  DEAD_LETTER = "DEAD_LETTER",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED"
}

export enum WorkflowPriority {
  CRITICAL = "CRITICAL",
  HIGH = "HIGH",
  NORMAL = "NORMAL",
  BACKGROUND = "BACKGROUND",
  BATCH = "BATCH"
}

export enum WorkflowQueueName {
  HIGH_PRIORITY = "HIGH_PRIORITY",
  AI_PARSING = "AI_PARSING",
  SEARCH_REINDEX = "SEARCH_REINDEX",
  ANALYTICS = "ANALYTICS",
  LOW_PRIORITY = "LOW_PRIORITY"
}
