export enum EventTypes {
  SUBMISSION_CREATED = 'SUBMISSION_CREATED',
  SUBMISSION_STATUS_UPDATED = 'SUBMISSION_STATUS_UPDATED',
  INTERVIEW_SCHEDULED = 'INTERVIEW_SCHEDULED',
  INTERVIEW_FEEDBACK_ADDED = 'INTERVIEW_FEEDBACK_ADDED',
  OFFER_STATUS_UPDATED = 'OFFER_STATUS_UPDATED',
  JOINING_STATUS_UPDATED = 'JOINING_STATUS_UPDATED',

  CANDIDATE_CREATED = 'CANDIDATE_CREATED',
  CANDIDATE_UPDATED = 'CANDIDATE_UPDATED',
  CANDIDATE_ARCHIVED = 'CANDIDATE_ARCHIVED',

  REQUIREMENT_CREATED = 'REQUIREMENT_CREATED',
  REQUIREMENT_UPDATED = 'REQUIREMENT_UPDATED',
  REQUIREMENT_ARCHIVED = 'REQUIREMENT_ARCHIVED',

  CLIENT_CREATED = 'CLIENT_CREATED',
  CLIENT_UPDATED = 'CLIENT_UPDATED',
  CLIENT_ARCHIVED = 'CLIENT_ARCHIVED',

  VENDOR_CREATED = 'VENDOR_CREATED',
  VENDOR_UPDATED = 'VENDOR_UPDATED',
  VENDOR_ARCHIVED = 'VENDOR_ARCHIVED',

  RECRUITER_CREATED = 'RECRUITER_CREATED',
  RECRUITER_UPDATED = 'RECRUITER_UPDATED',
  RECRUITER_ARCHIVED = 'RECRUITER_ARCHIVED'
}
