export enum IntakeEventType {
  INTAKE_RECEIVED = "INTAKE_RECEIVED",
  INTAKE_NORMALIZED = "INTAKE_NORMALIZED",
  ATTACHMENTS_EXTRACTED = "ATTACHMENTS_EXTRACTED",
  ENTITY_CLASSIFIED = "ENTITY_CLASSIFIED",
  ENTITY_EXTRACTED = "ENTITY_EXTRACTED",
  ENTITY_VALIDATED = "ENTITY_VALIDATED",
  ENTITY_CREATED = "ENTITY_CREATED",
  RELATIONSHIP_CREATED = "RELATIONSHIP_CREATED",
  BUSINESS_GRAPH_UPDATED = "BUSINESS_GRAPH_UPDATED",
  EVENT_PUBLISHED = "EVENT_PUBLISHED",
  MATCH_REQUESTED = "MATCH_REQUESTED",
  INTAKE_FAILED = "INTAKE_FAILED",
}
